### ISSUE TITLE
"split" function/mutation

### ISSUE THREAD

**Issue by antonsoroko** [i96751414/script.flix.magneto#13]
jfyi:
`$ python3 provider_test.py xpath --rows ".//table/tr" "td[2]/font/text()" "https://thepiratebay10.org/search/Video%202023/1/99/200"`
gives
`INFO - Uploaded 01-05 14:16, Size 2.06 GiB, ULed by`

so "split" function/mutation is needed to parse things like that.

**Comment by i96751414** [comment]
I added 3e7f4a0 to support replacing strings.

For your case you would have to use mutate:
```json
      "mutate": {
        "size": "{size:r/.*?Size (.+?),.*/\\1/}"
      }
```

**Comment by antonsoroko** [comment]
@i96751414 works good!
although for other (more simple) cases it would be nice to have a simple `split` function.
of course regexp will be cover many (or most of the) cases, but it also will look bulky. that's from my experience of creating providers for elementum burst. 
so it is up to you to decide if you want to implement it. (if not - you we can close the issue.)

thanks.

**Comment by i96751414** [comment]
I think I will add support to dedicated functions, but that requires considerable changes for the formatter. Lets keep this one opened for now

**Comment by i96751414** [comment]
Ok, I ended up changing the behavior with efeb110

After this commit, functions are now supported and you should use them as specified [here](https://github.com/i96751414/script.flix.magneto?tab=readme-ov-file#functions-support).

For your particular case, the following should work:
```json
"mutate": {
    "size": "{size:replace('.*?Size (.+?),.*', '\\1')}"
}
```

**Comment by antonsoroko** [comment]
nice!
btw, any example of how to use `split`+`get`?
