### ISSUE TITLE
[resolved] I need help creating a provider

### ISSUE THREAD

**Issue by icarok99** [i96751414/script.flix.magneto#14]
If someone helps me like this, I'll know and I'll be able to add others.

https://comando4kfilmes.org/?s=QUERY
https://comando4kfilmes.org/?s=Iron+man

https://ontorrent.org/?s=QUERY
https://ontorrent.org/?s=Iron+man

https://ontorrent.org/?s=QUERY
https://ontorrent.org/?s=Iron+man

   
I need help with this part 

```
[
  {
    "name": "Comando 4k filmes",
    "base_url": "https://comando4kfilmes.org",
    "results_parser": {
      "url": "",
      "rows": "'",
      "data": {
        "torrent_url": "",
        "title": "",
        "seeds": "",
        "leeches": "",
        "size": ""
      }
    },
    "additional_parsers": [
      {
        "url": "{torrent_url}",
        "data": {
          "magnet": ""
        }
      }
    ],
    "keywords": {
      "movie": "{title:br} {year}",
      "show": "{title:br}",
      "season": "{title:br} {season:02} temporada",
      "episode": "{title} S{season:02}E{episode:02}"
    },
    "attributes": {
      "color": "FFF14E13",
      "icon": "provider_icons/comando4kfilmes.png"
    }
  }
]
```

**Comment by addon-rajada** [comment]
@icarok99 
You need to learn how to parse xml/html using xpath

You can use these parsers i did as an example:
```json
[
        {
		"name": "BitSearch", "base_url": "https://bitsearch.to",
		"results_parser": {
		  "url": "/search?q={query:q}&category=1&subcat=2&sort=seeders",
		  "rows": ".//div[@class='w3-col s12 mt-1']/li/div/div/../..",
		  "data": {
			"magnet": "div[2]/a[2]/@href",
			"title": "div[1]/div/h5/a/text()",
			"seeds": "div[1]/div/div/div/div[3]/font/text()",
			"leeches": "div[1]/div/div/div/div[4]/font/text()",
			"size": "div[1]/div/div/div/div[2]/text()"
		  }
		},
		"keywords": { "movie": "{title} {year}", "show": "{title}", "season": "{title} S{season:02}", "episode": "{title} S{season:02}E{episode:02}" },
		"attributes": { "color": "FF6AC045", "icon": "provider_icons/default.png"}
	},

	{
		"name": "Insanos Torrent", "base_url": "https://insanostorrent.com",
		"results_parser": {
		 	"url": "/?s={query:q}", "type": "html",
		 	"rows": ".//div[@class='mblock-content']/div[@class='box-filme-item']/div[1]/div[@class='filme-rating']/div/span/../../..",
		 	"data": {
		 	  "torrent_url": "a[1]/@href",
		 	  "title": "div[3]/img/@alt"
		 	}
			},
		"additional_parsers": [
			{
			  "url": "{torrent_url}", "type": "html",
			  "data": {
				"magnet": ".//div[@class='items']/div[@id='categoria']/div[@class='row row-single']/div/input[@type='button']/@value"
			  }
			}
		],
		"keywords": { "movie": "{title} {year}", "show": "{title}", "season": "{title} S{season:02}", "episode": "{title} S{season:02}E{episode:02}" },
		"attributes": { "color": "FFF25F2A", "icon": "provider_icons/default.png" }
	}
]
```

**Comment by icarok99** [comment]
> @icarok99 You need to learn how to parse xml/html using xpath
> 
> You can use these parsers i did as an example:
> 
> ```json
> [
>         {
> 		"name": "BitSearch", "base_url": "https://bitsearch.to",
> 		"results_parser": {
> 		  "url": "/search?q={query:q}&category=1&subcat=2&sort=seeders",
> 		  "rows": ".//div[@class='w3-col s12 mt-1']/li/div/div/../..",
> 		  "data": {
> 			"magnet": "div[2]/a[2]/@href",
> 			"title": "div[1]/div/h5/a/text()",
> 			"seeds": "div[1]/div/div/div/div[3]/font/text()",
> 			"leeches": "div[1]/div/div/div/div[4]/font/text()",
> 			"size": "div[1]/div/div/div/div[2]/text()"
> 		  }
> 		},
> 		"keywords": { "movie": "{title} {year}", "show": "{title}", "season": "{title} S{season:02}", "episode": "{title} S{season:02}E{episode:02}" },
> 		"attributes": { "color": "FF6AC045", "icon": "provider_icons/default.png"}
> 	},
> 
> 	{
> 		"name": "Insanos Torrent", "base_url": "https://insanostorrent.com",
> 		"results_parser": {
> 		 	"url": "/?s={query:q}", "type": "html",
> 		 	"rows": ".//div[@class='mblock-content']/div[@class='box-filme-item']/div[1]/div[@class='filme-rating']/div/span/../../..",
> 		 	"data": {
> 		 	  "torrent_url": "a[1]/@href",
> 		 	  "title": "div[3]/img/@alt"
> 		 	}
> 			},
> 		"additional_parsers": [
> 			{
> 			  "url": "{torrent_url}", "type": "html",
> 			  "data": {
> 				"magnet": ".//div[@class='items']/div[@id='categoria']/div[@class='row row-single']/div/input[@type='button']/@value"
> 			  }
> 			}
> 		],
> 		"keywords": { "movie": "{title} {year}", "show": "{title}", "season": "{title} S{season:02}", "episode": "{title} S{season:02}E{episode:02}" },
> 		"attributes": { "color": "FFF25F2A", "icon": "provider_icons/default.png" }
> 	}
> ]
> ```

If I to try  learn, my brain fries, it's a lot for a Bahian.😂
