### ISSUE TITLE
Allow parsing multiple pages instead of a single page only

### ISSUE THREAD

**Issue by i96751414** [i96751414/script.flix.magneto#15]
Currently the plugin only supports parsing a single page for getting the main rows (results).
The idea is to extend the scraper so it supports fetching results from different pages.

**Comment by antonsoroko** [comment]
so https://github.com/i96751414/script.flix.magneto?tab=readme-ov-file#using-an-additional-parser does not do this already?

i though that `"torrent_url": "td[1]/a[2]/@href"`, will point to sub page, magneto opens sub page and then `"magnet": .//main/div/ul/li/a/@href"` will find magnet link.
