### ISSUE TITLE
[SUGGESTION] expand keyword possibilities 

### ISSUE THREAD

**Issue by icarok99** [i96751414/script.flix.magneto#16]
The idea of expanding the keyword is to make it possible to use 2 keywords for movies and other options.

Small example: 
"movie": "{title:br} {year}",
"movie2": "{title:en} {year}",

**Comment by icarok99** [comment]
A means of translation so that it is possible to use this type of keyword.

**Comment by i96751414** [comment]
Better yet - something like:

```json
"movie": ["{title:br} {year}", "{title:en} {year}"]
```

That would be very easy to support, I think.

**Comment by i96751414** [comment]
By the way, that is not the way you get the title by country. Please have a look at #4

**Comment by icarok99** [comment]
> By the way, that is not the way you get the title by country. Please have a look at #4

Now it's explained why before I didn't  I couldn't get a title from my country, I was using {title:br}. Thank you very much, now I will get the title in my country's language.

**Comment by icarok99** [comment]
> Você ainda acha que isso é necessário?

Yes, because sometimes Brazilian providers use the original title, sometimes the title translated into my language. With 2 search modes help

**Comment by icarok99** [comment]
Here is an example because of name torrent next to the title, I can't find the movie using {title.br} I have to use {title:original}

![IMG_20240221_184420](https://github.com/i96751414/script.flix.magneto/assets/46580318/f6518573-3ebc-423d-a99a-2685516805be)
