### ISSUE TITLE
How to setup providers.json if there's no rows

### ISSUE THREAD

**Issue by uomar8** [i96751414/script.flix.magneto#3]
parse JSON

[
  {
    "Name": "movie name 1",
    "Magnet": "magnet link 1"
  },
  {
    "Name": "movie name 2",
    "Magnet": "magnet link 2"
  }
]

And my providers.json

      "type": "json",
      "rows": "",
      "data": {
        "title": "./Name/text()",
        "magnet": "./Magnet/text()"
      }
    But it doesn't work what should be in "rows" in case like this?

**Comment by i96751414** [comment]
Hi. You will need to specify a way of parsing all rows (it cant be empty). The 'data' fields are then parsed for each row.

**Comment by uomar8** [comment]
@i96751414
I'm trying to use https://github.com/Ryuk-me/Torrents-Api if you could help me with "rows"? Please 

I tried a lot of ways can't figure out how to do it

**Comment by i96751414** [comment]
Hi. I had a look, but the api seems not to be online.

**Comment by i96751414** [comment]
I will create a tester so users can test their providers without starting kodi. Stay tuned.

**Comment by uomar8** [comment]
> I will create a tester so users can test their providers without starting kodi. Stay tuned.

That would be great can't wait to try it thank you

Also I want to mention you're right the Try api doesn't work you have to click on "deploy on Heroku"

**Comment by i96751414** [comment]
Hi. Please have a look at https://github.com/i96751414/script.flix.magneto#testing-the-provider

**Comment by uomar8** [comment]
"rows": "./*",
      "data": {
        "title": ".//Name/text()",
        "size": ".//Size/text()",
        "seeds": ".//Seeders/text()",
        "magnet": ".//Magnet/text()"

Now it works

**Comment by uomar8** [comment]
> Hi. I had a look, but the api seems not to be online.
> Edit: I was using the wrong url. Problably rows here will be "./"

It works thank you
