### ISSUE TITLE
Search by title instead of original title

### ISSUE THREAD

**Issue by uomar8** [i96751414/script.flix.magneto#4]
It search by original title instead of title
![20210903_183312](https://user-images.githubusercontent.com/7046347/132031025-2894367f-4e52-4b0d-8e35-d503436fb89f.jpg)

I tried title.GB but didn't work

**Comment by i96751414** [comment]
All the titles available are provided, if I am not mistaken. You can try to access the English title with title.en

**Comment by uomar8** [comment]
> All the titles available are provided, if I am not mistaken. You can try to access the English title with title.en

Oh i got confused by title.<country> 
I just tried title.en it still use original title instead of English title

**Comment by i96751414** [comment]
Sorry, I was not correct. The codes follow ISO 3166-1. So a valid one is title.us or titles.gb. when the code does not exists, it falls back to the original title
