### ISSUE TITLE
a4kSubtitles works with movies but doesn't work with tv shows 

### ISSUE THREAD

**Issue by uomar8** [i96751414/script.flix.magneto#5]
a4kSubtitles works with movies but doesn't work with tv shows it says IMDB ID is not provided

Edit: it might flix subtitle doesn't work with tv shows as well

**Comment by i96751414** [comment]
I am not sure tmdb provides IMDb id for episodes. Flix subtitles should work for everything (you need to setup your account on opensubtitles). If you find some problem with it, please report it on flix plugin.
