### ISSUE TITLE
Making use of existing providers

### ISSUE THREAD

**Issue by borealopithecus** [i96751414/script.flix.magneto#6]
Hello,

Do you have any idea on how to transfer existing providers (say those for the Elementum Burst addon) to the format required by Magneto? I've been trying to think of a way of a programmatic way to do this but given my lack of expertise in the JSON schemas I don't even know where to start.

If you have any idea on what first step could be taken, that'd be amazing.

Thanks.

**Comment by borealopithecus** [comment]
I think this is a non-trivial problem and hence I will spend more time trying to solve it before inquiring for aid.

**Comment by addon-rajada** [comment]
A little late, but i just found a way to port elementum providers to Flix.
As it works at Rajada, it will likely work with Burst.
You can check it [here](https://github.com/addon-rajada/script.elementum.rajada/compare/36b19091b4fef81e954967ae7b5d9b89b0c5ed20..6f3c47016a2f59967bf62efcbe24941360194ced).

The Rajada and Flix dialogs are running concurrently.
By now `flix_main.py` is converting flix requests to elementum general query search payload, but it can be enhanced.
